# Generated by Django 5.0.1 on 2024-01-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
